version: '3.8'

services:
  go-server:
    build: .
    ports:
      - '8080:8080'
    environment:
      - GO_ENV=production
    networks:
      - go-network

networks:
  go-network:
    driver: bridge
